CREATE TABLE IF NOT EXISTS ?eras
( era_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  era_name VARCHAR(128) NOT NULL,
  deleted_dt TIMESTAMP NULL DEFAULT NULL )
ENGINE=MyISAM 
DEFAULT CHARACTER SET = utf8;

